### ISSUE TITLE
Type erasure needed for TableAccess trait and all table "iter" methods

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit-rust#148]
Several interfaces return objects implementing `Iterator`.  Currently, the functions return a type for which `Iterator` is implemented, giving the mistaken impression that there's a `struct` whose implementation details need to be considered in client code.  For most of these, however, all client code needs to worry about is that they `impl Iterator`.  (In fact, I think this is true for all of them...)

We can make these types `pub(crate)`, preventing the names from leaking from the library.  Change the function declarations to reflect returning `impl Iterator<type=X>` (or `Box<dyn ..>` when  the function is declared in a trait).

These changes won't break API as the interface remains unchanged.

**Comment by MomoLangenstein** [comment]
+1 (and if you want to return impl Trait from inside a trait, you can do an … imperfect workaround. You can return an associated type which is then set to impl Trait inside the implementations)

**Comment by molpopgen** [comment]
Removing this from the next release milestone.  It is tedious to get right.  There's a bunch of lifetime elision to worry about.
