### ISSUE TITLE
Provenance table behavior with empty records

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit-rust#150]
Currently, adding provenance with an empty record raises an error.  This behavior differs from tskit-python.  Should we change it?  IMO, it is unclear what the client intended re: provenance here, signalling an error happening somewhere in the work flow?

**Comment by molpopgen** [comment]
cc @benjeffery @jeromekelleher -- I noticed that the Python API is fine with empty records for provenance.  However, that's "weird" in a few senses.  Here, I've been raising an error, because one is probably making a mistake by adding an empty entry to the provenance table.  Wondering if this should a.) be changed on the Python side, b.) changed here, c.) neither?

**Comment by jeromekelleher** [comment]
I don't have a strong opinion here @molpopgen - probably the Python behaviour is just an oversight. I wouldn't worry about the inconsistency though, we'll have to be pretty relaxed about what we accept as provenance in practise probably (should we ever decide we want to do something with it, which I'm skeptical about)

**Comment by molpopgen** [comment]
Thanks.  In my mind, the only issue that it brings up is that if something is created in Python, and then processed in rust, there's the possibility of getting an error when trying to process a providence row with an empty record.

**Comment by jeromekelleher** [comment]
There's no restrictions made at the C level, so I think Rust will have to assume that there could basically be anything in there.

**Comment by molpopgen** [comment]
So right now, we are assuming that valid strings are in there, meaning valid utf8.  Allowing more general notions of "records" will require some tweaking.
