### ISSUE TITLE
Update tree structures to use "virtual root"?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-rust#170]
I'm not sure how much has been done here with the representation of trees (if anything), but wanted to check if any updates were needed to take advantage of the virtual root (and perhaps traversal functions?) added in https://github.com/tskit-dev/tskit/pull/1704

I'm happy to help where I can.

**Comment by molpopgen** [comment]
#183 updated the C API and only the root iterator initialization needed changing.  I used the "get left root" function for that.  Keeping this issue open in case something else pops up...

**Comment by molpopgen** [comment]
Note: virtual root is a `tsk_id_t`, so we'll get to re-use our macros to make a newtype out of this.

**Comment by molpopgen** [comment]
> Note: virtual root is a `tsk_id_t`, so we'll get to re-use our macros to make a newtype out of this.

Actually, it is a "root"-like thing, so `NodeId` covers it.
