### ISSUE TITLE
C API for node iteration forthcoming

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit-rust#177]
@jeromekelleher pointed out that the next C API release will have C API functions for iterating over nodes in a tree.  We should explore using this API, replacing the existing rust code for preorder traversal if it works out.  If it does work, then we can get other traversal orders "for free".

The cost is more `unsafe` code blocks.

**Comment by jeromekelleher** [comment]
Two things worth bearing in mind @molpopgen 

1. There's only preorder and postorder currently (have issue for inorder: https://github.com/tskit-dev/tskit/issues/1797)
2. There's a O(n) memory overhead. If Rust has nice iteration abstractions to avoid this that are efficient, then might be worth sticking with whatever you have (if you have anything!)

**Comment by jeromekelleher** [comment]
There's that, but also the array you need to malloc to get the results back. This example is idiomatic: https://github.com/tskit-dev/tskit/blob/b8d664712244f2eaeaab6fb4d19f84001c676738/c/tskit/trees.c#L3594

**Comment by molpopgen** [comment]
Ah, I see.  Yeah, the rust iterator has a "current node" field that it "yields" until we hit the end.

Still, the new API will be an easy path for postorder until I/someone reach the activation energy for a pure rust version.

**Comment by molpopgen** [comment]
@jeromekelleher -- working on this in #186
