### ISSUE TITLE
Start tree iterator at specified location

### ISSUE THREAD

**Issue by molpopgen** [tskit-dev/tskit-rust#435]
We need public API for:

* starting a tree iterator at the i-th tree
* starting a tree iterator at the first tree containing position "x"

**Comment by molpopgen** [comment]
These functions would be linear time at first, but eventually much faster (for free), once I get some back-end stuff into upstream.  The upstream API has the position-wise function, so we should just do that at first?

**Comment by molpopgen** [comment]
Removing from 0.12.0.  We may just wait for the next C API release, assuming that efficient seek is included in that.

**Comment by bguo068** [comment]
This would be a great addition to the existing functions of rust bindings of tskit. I am also wondering whether it is of interest to implement a `keep_intervals` method for the `TreeSequence` or `TableCollection` structs.

There is a Python API in tskit (https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.keep_intervals) and there is not a C API (or a rust binding for that). But it appears that the method might be implemented by mimicking the Python code: https://tskit.dev/tskit/docs/stable/_modules/tskit/tables.html#TableCollection.keep_intervals .

**Comment by molpopgen** [comment]
> This would be a great addition to the existing functions of rust bindings of tskit. 

The seeking is doable "now" with the main branch.-- tskit-rust is based on C API 1.1.2.  One could call the low-level C function now to apply `tsk_tree_seq` directly. I do intend a rust wrapper for the next release, although progress towards that release is currently slow.

I am also wondering whether it is of interest to implement a `keep_intervals` method for the `TreeSequence` or `TableCollection` structs.
> 
> There is a Python API in tskit (https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TreeSequence.keep_intervals) and there is not a C API (or a rust binding for that). But it appears that the method might be implemented by mimicking the Python code: https://tskit.dev/tskit/docs/stable/_modules/tskit/tables.html#TableCollection.keep_intervals .

A PR for this would be welcome.

One current goal is to improve the rust back end to isolate more calls to `unsafe` into an internal `sys` module.  I haven't had much time to devote to this crate lately, but what effort I have  put in has gone towards this and not new features.

**Comment by molpopgen** [comment]
This is completed via #613.

We do not currently support a `Tree` object "jumping" from a current iteration point to another.  To fix that would require some back end changes to how we manage the tree iteration.

@bguo068 if you would like to open a feature request for "keep indexes", feel free to do so.  Also, if you would like to have access to the new features from #613, let me know and I can publish an alpha release of the 0.15.x series.

**Comment by bguo068** [comment]
Thank you @molpopgen . The new commit works nicely.  Also I am able to use git + rev  to set the dependency to point the newest version from the main branch. So no pressure for the alpha release. 

```toml
[dependencies]
tskit = {git = "https://github.com/tskit-dev/tskit-rust.git", rev = "7a36294bdcdfd137b314b7426b5c4eca9f9d2420", features = ["bindings"]}
streaming-iterator = "0.1.9"
```

I will put the `keep_intervals` feature in a new issue. I will learn to contribute to this repo with a PR once I am there. 

Thank you again for the instant response and help!!
